# Generated by Django 3.0.3 on 2021-02-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylish_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Contact', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
                ('Image1', models.ImageField(upload_to='img/images')),
                ('Image2', models.ImageField(upload_to='img/images')),
                ('Image3', models.ImageField(upload_to='img/images')),
                ('Image4', models.ImageField(upload_to='img/images')),
                ('Image5', models.ImageField(upload_to='img/images')),
                ('Status', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Stylish_details',
            },
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default=None, max_length=100)),
                ('LastName', models.CharField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
                ('mobile', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('City', models.CharField(default=None, max_length=100)),
                ('State', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'User_details',
            },
        ),
    ]
