# Generated by Django 3.0.3 on 2021-02-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0002_stylish_details_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='ExpiryDate',
            field=models.DateField(default=None),
        ),
    ]
