# Generated by Django 3.0.3 on 2021-02-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0003_user_details_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylish_details',
            name='Speciality',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
