# Generated by Django 3.0.3 on 2021-02-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0004_stylish_details_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haflyear', models.IntegerField(default=None)),
                ('year', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'Subscriptions',
            },
        ),
    ]
