# Generated by Django 3.0.3 on 2021-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0006_auto_20210210_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='ChatStatus',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
