# Generated by Django 3.0.3 on 2021-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0007_user_details_chatstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default=None, max_length=100)),
                ('Context', models.CharField(default=None, max_length=100)),
                ('ContextImage', models.ImageField(upload_to='img/images/ChatImages')),
                ('Uid', models.CharField(default=None, max_length=100)),
                ('Sid', models.CharField(default=None, max_length=100)),
                ('Datetime', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Chat_details',
            },
        ),
    ]
