# Generated by Django 3.0.3 on 2021-02-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0008_chat_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_details',
            name='MsgFrom',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
