# Generated by Django 3.0.3 on 2021-02-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0010_auto_20210212_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_details',
            name='ContextImage',
            field=models.TextField(default=None),
        ),
    ]
