# Generated by Django 3.0.3 on 2021-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0011_auto_20210213_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
