# Generated by Django 3.0.3 on 2021-02-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kneearth', '0013_auto_20210213_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='Status',
        ),
    ]
